name: 🚀 Laravel Kink  Deploy to CyberPanel

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy Laravel App
    runs-on: ubuntu-latest

    steps:
      - name: 📦 Checkout Repo
        uses: actions/checkout@v4

      - name: 🔐 Setup SSH Key
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.DEPLOY_KEY }}

      - name: 📤 Deploy to CyberPanel via SSH
        run: |
          ssh -o StrictHostKeyChecking=no root@173.212.213.153 << 'EOF'
            cd /home/biotaplant.com/kink2.biotaplant.com

            echo "📥 Pulling latest code..."
            git pull origin main

            echo "📦 Installing Composer dependencies..."
            composer install --no-interaction --prefer-dist --optimize-autoloader

            echo "🔧 Running Laravel setup commands..."
            php artisan migrate --force
            php artisan config:cache
            php artisan route:cache
            php artisan view:cache
          EOF
